# Generated by Django 2.1.7 on 2019-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190321_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumb',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
